### ISSUE TITLE
Alethe proofs rejected with rule mod_simplify

### ISSUE THREAD

**Issue by rodrigo7491** [usi-verification-and-security/golem#55]
The alethe proofs for [chc-LIA_366](https://github.com/chc-comp/chc-comp23-benchmarks/blob/main/LIA-lin/chc-LIA-Lin_366.smt2.gz) and [chc-LIA_379](https://github.com/chc-comp/chc-comp23-benchmarks/blob/main/LIA-lin/chc-LIA-Lin_379.smt2.gz), from CHC-COMP 2023, are being rejected by [carcara](https://github.com/ufmg-smite/carcara).

Production command: `golem --logic QF_LIA --print-witness --proof-format alethe [file.smt2]`
Checking command: `carcara check --allow-int-real-subtyping --expand-let-bindings [proof.alethe] [file.smt2]`

Checking output for chc-LIA_366:

```
[ERROR] checking failed on step 't77427' with rule 'mod_simplify': expected term '1' to be numerical constant 9.0
invalid
```

Checking output for chc-LIA_379:

```
[ERROR] checking failed on step 't6544' with rule 'mod_simplify': expected term '26' to be numerical constant 63.0
invalid
```

**Comment by blishko** [comment]
While the issue with modulo has been fixed, it revealed another problem on `chc-LIA-Lin_366`. I will create a separate issue for that.
