### ISSUE TITLE
Golem returns wrong sat result

### ISSUE THREAD

**Issue by jena-kling** [usi-verification-and-security/golem#84]
Hey,
it seems that after the last fix golem can still return UNSAT for SAT instances:
```
( set-logic HORN )
(declare-fun pred (Int) Bool)

(assert (not (pred 0)))
(assert  (=> ( forall ( ( var0 Int ) )  ( = 0 var0)  ) (pred 0)))

(check-sat)
```
I invoked 
```
$ ~/golem/build/golem --validate test.smt2 
unsat
Internal witness validation successful!
```
A model would be to simply set `pred(x) = false`.

**Comment by blishko** [comment]
This formula is also outside of the supported fragment, as Golem does not support quantified constraint in a Horn clause.
The universal quantifier can only occur before the implication, not inside it.
I will check if this can be easily fixed.

**Comment by blishko** [comment]
Golem will now report error on this input.
